tls:
  certificates:
     -   certFile: /etc/traefik/certs/_wildcard.bojemoi.lab+1.pem
         keyFile: /etc/traefik/certs/_wildcard.bojemoi.lab+1-key.pem
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/_wildcard.bojemoi.lab+1.pem
        keyFile: /etc/traefik/certs/_wildcard.bojemoi.lab+1-key.pem

