#cloud-config
hostname: ${HOSTNAME}

users:
  - name: deploy
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2E... deploy@bojemoi

package_update: true
package_upgrade: true

packages:
  - curl
  - git
  - vim

runcmd:
  - echo "Setup complete"

timezone: Europe/Paris

